# Site settings
title: Ankit P. &raquo; I've no idea what I do
description: Yet another software developer.
url: "https://ankit.pl"

# User settings
username: Ankit P.
name: ankit.pl
user_description: Yet another software developer.
user_title: Software Developer
email: hello@ankit.pl
github: https://github.com/ankitpokhrel
linkedin: https://www.linkedin.com/in/apkl/
twitter:
medium: https://medium.com/@ankitpokhrel
wordpress: https://profiles.wordpress.org/ankitpokhrel
stackoverflow: https://stackoverflow.com/users/2607359/konsole

exclude: ['package.json', 'src' , 'node_modules', '.idea']
